Get_URL = "https://reqres.in/api/users?page=2"
Post_URL = "https://reqres.in/api/users"
Get_URL1 = "https://reqres.in/api/users/2"
Put_URL1 = "https://reqres.in/api/users/2"
Post_URL1= "https://reqres.in/api/register"
Patch_URL1= "https://reqres.in/api/users/2"
Delete_URL1= "https://reqres.in/api/users/2"
Post_URL2= "https://reqres.in/api/login"
Get_URL2 = "https://reqres.in/api/users?delay=3"
Get_URL3  ="https://reqres.in/api/users/23"
Get_URL4  ="https://reqres.in/api/users/23"
Get_URL5  ="https://reqres.in/api/users/23"
Get_URL6  ="https://reqres.in/api/users/23"
Get_URL7  ="https://reqres.in/api/users/23"
Get_URL8  ="https://reqres.in/api/users/23"